# Generated by Django 4.0.1 on 2022-03-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firest_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('emp_id', models.IntegerField()),
            ],
        ),
    ]
